#!/bin/sh

red=$'\e[1;31m'
mag=$'\e[1;35m'
end=$'\e[0m'
bld=$'\e[1m'
dim=$'\e[2m'

symlinks=(atom bin fish npm git homebrew vim)

hydrate() {
  for src in ${symlinks[@]}; do
    stow --restow --target=$HOME $src
    printf "${dim}[link]${end} $src\n"
  done
}

printf "install dotfiles? ${bld}[y/n]${end} ${red}>>${end} "

while true; do
  read yn
  case $yn in
    [Yy]*) break ;;
    [Nn]*) exit ;;
    *) printf "${bld}[y/n]${end} ${red}>>${end} " ;;
  esac
done

hydrate
brew bundle --file=$HOME/.Brewfile

printf "${mag}[done]${end} 🏄🏽"
