cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/homebrew-php'
tap 'caskroom/versions'
tap 'fisherman/tap'

brew 'coreutils'
brew 'findutils'
brew 'fish'
brew 'fisherman'
brew 'fzf'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'grep', args: ['with-default-names']
brew 'moreutils'
brew 'node'
brew 'openssh'
brew 'php-code-sniffer'
brew 'rbenv'
brew 'rsync'
brew 'stow'
brew 'swiftlint'
brew 'the_silver_searcher'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'z'

cask 'atom'
cask 'flux'
cask 'google-chrome'
cask 'iterm2-beta'
cask 'keepingyouawake'
cask 'spectacle'
