cask_args appdir: '/Applications'

#taps
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'fisherman/tap'

# formulas
brew 'bash'
brew 'coreutils', args: ['with-default-names']
brew 'direnv'
brew 'findutils'
brew 'fish'
brew 'fisherman'
brew 'fzf'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'grep', args: ['with-default-names']
brew 'less'
brew 'moreutils', args: ['with-default-names']
brew 'nano'
brew 'node'
brew 'openssh'
brew 'python'
brew 'rbenv'
brew 'rsync'
brew 'stow'
brew 'swiftlint'
brew 'the_silver_searcher'
brew 'vim' , args: ['--override-system-vi']
brew 'wget'
brew 'yarn'
brew 'z'

# casks
cask 'atom'
cask 'font-hack'
cask 'iterm2-beta'
cask 'flux'
cask 'google-chrome'
cask 'keepingyouawake'
cask 'spectacle'
